version: '3.9'

services:
  node:
    container_name: tic-tac-toe-monorepo-node
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 16
    volumes:
      - ..:/workspace:cached
    env_file: ../.env
    command: sleep infinity
